apiVersion: v1
kind: Service
metadata:
  labels:
    io.kompose.service: client
  name: client
spec:
  ports:
    - name: "7096"
      port: 7096
      targetPort: 80
  selector:
    io.kompose.service: client
