apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    io.kompose.service: client
  name: client
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: client
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        io.kompose.network/harmony-default: "true"
        io.kompose.service: client
    spec:
      containers:
        - env:
            - name: ASPNETCORE_ENVIRONMENT
              value: Development
            - name: ASPNETCORE_HTTPS_PORT
              value: "7096"
            - name: ASPNETCORE_Kestrel__Certificates__Default__Password
              value: HarmonyTeamsSecretKey
            - name: ASPNETCORE_Kestrel__Certificates__Default__Path
              value: /https/harmony.pfx
            - name: ASPNETCORE_URLS
              value: https://+:443;http://+:80
          image: client
          name: harmony.client
          ports:
            - containerPort: 80
              hostPort: 7096
              protocol: TCP
          volumeMounts:
            - mountPath: /https
              name: client-claim0
      restartPolicy: Always
      volumes:
        - name: client-claim0
          persistentVolumeClaim:
            claimName: client-claim0
