apiVersion: v1
kind: Service
metadata:
  labels:
    io.kompose.service: notifications
  name: notifications
spec:
  ports:
    - name: "7121"
      port: 7121
      targetPort: 443
  selector:
    io.kompose.service: notifications
