apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    io.kompose.service: notifications
  name: notifications
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: notifications
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        io.kompose.network/harmony-default: "true"
        io.kompose.service: notifications
    spec:
      containers:
        - env:
            - name: ASPNETCORE_ENVIRONMENT
              value: Development
            - name: ASPNETCORE_HTTPS_PORT
              value: "7121"
            - name: ASPNETCORE_Kestrel__Certificates__Default__Password
              value: HarmonyTeamsSecretKey
            - name: ASPNETCORE_Kestrel__Certificates__Default__Path
              value: /https/harmony.pfx
            - name: ASPNETCORE_URLS
              value: https://+:443;http://+:80
            - name: AppEndpointConfiguration__HarmonyApiEndpoint
              value: https://harmony.api:443/
            - name: BrokerConfiguration__Host
              value: harmony_rabbitmq
            - name: ConnectionStrings__HarmonyJobsConnection
              value: Server=harmony_sql_server;database=Harmony.Notifications.Jobs;User Id=sa;Password=%HarmonyTeams100;TrustServerCertificate=True
            - name: ElasticConfiguration:Uri
              value: http://elasticsearch:9200
          image: notifications
          name: harmony.notifications
          ports:
            - containerPort: 443
              hostPort: 7121
              protocol: TCP
          volumeMounts:
            - mountPath: /https
              name: notifications-claim0
      restartPolicy: Always
      volumes:
        - name: notifications-claim0
          persistentVolumeClaim:
            claimName: notifications-claim0
