apiVersion: v1
kind: Service
metadata:
  labels:
    app: signalr
  name: signalr
spec:
  type: LoadBalancer
  ports:
    - name: "7262"
      port: 7262
      targetPort: 443
  selector:
    app: signalr
