apiVersion: v1
kind: Service
metadata:
  labels:
    app: sourcecontrol
  name: harmony-integrations-sourcecontrol
spec:
  ports:
    - name: "443"
      port: 443
      targetPort: 443
  selector:
    app: sourcecontrol
