version: "3.9"
services:
   harmony_api:
    build: 
        context: .
        dockerfile: Web\Harmony.Api\Dockerfile
        args:
          BUILD_CONFIGURATION: Debug
    container_name: harmony.api
    ports:
        - "7097:443"
        - "7098:80"
    environment:
        - ASPNETCORE_ENVIRONMENT=Development
        - ASPNETCORE_URLS=https://+:443;http://+:80
        - ASPNETCORE_HTTPS_PORT=7097
        - ASPNETCORE_Kestrel__Certificates__Default__Password=HarmonyTeamsSecretKey 
        - ASPNETCORE_Kestrel__Certificates__Default__Path=/https/harmony.pfx 
        - ConnectionStrings__HarmonyConnection=Server=harmony_sql_server;database=harmony;User Id=sa;Password=%HarmonyTeams100;TrustServerCertificate=True
    volumes:
        - $USERPROFILE\.aspnet\https:/https/
    depends_on:
        - sql_server
   sql_server:
    image: "mcr.microsoft.com/mssql/server:2022-latest"
    container_name: harmony_sql_server
    environment:
      - ACCEPT_EULA=y
      - SA_PASSWORD=%HarmonyTeams100
    volumes:
      - C:\SQL\harmony\data:/var/opt/mssql/data
      - C:\SQL\harmony\log:/var/opt/mssql/log
      - C:\SQL\harmony\secrets:/var/opt/mssql/secrets